databases:
  - name: GaiaGate-Main
    databaseName: gaiagate_main
    user: gaiagate_main_user

services:
  - type: web
    name: gaiagate
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gaiagate.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: GaiaGate-Main
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
