# Generated by Django 6.0 on 2025-12-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quaternion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
                ('w', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_subarea', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'F'), (6, 'G'), (7, 'H')], default=0)),
                ('level_day_night', models.IntegerField(choices=[(0, 'Day'), (1, 'Night')], default=0)),
                ('region', models.IntegerField(choices=[(1, 'Apotos'), (2, 'Holoska'), (3, 'Spagonia'), (4, 'Chun Nan'), (5, 'Shamar'), (6, 'Adabat'), (7, 'Eggmanland')], default=1)),
                ('stage_kind', models.IntegerField(choices=[(1, 'Main'), (2, 'Mission'), (5, 'Boss Maybe'), (6, 'Unknown')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vec3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('z', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headerinfo', models.CharField(default='00000000', max_length=8)),
                ('params', models.CharField(max_length=200)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unwiishedviewer.quaternion')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unwiishedviewer.stage')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='unwiishedviewer.vec3')),
                ('scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scale', to='unwiishedviewer.vec3')),
            ],
        ),
    ]
